CREATE TABLE jobs (
	job_id VARCHAR(255) PRIMARY KEY,
	job_title VARCHAR(255),
	employer_name VARCHAR(255),
	employer_website VARCHAR(255),
	job_publisher VARCHAR(255),
	job_employment_type VARCHAR(255),
	job_description VARCHAR(MAX) NOT NULL,
	job_posted_at VARCHAR(255),
	job_posted_at_datetime_utc DATETIME,
	job_rated_at_utc DATETIME NOT NULL,
	job_location VARCHAR(255),
	job_city VARCHAR(255),
	job_state VARCHAR(255),
	job_country VARCHAR(255),
	job_benefits VARCHAR(MAX),
	job_salary_string VARCHAR(255),
	job_min_salary INT,
	job_max_salary INT,
	job_salary_period VARCHAR(255),
	job_score TINYINT NOT NULL,
	job_score_reasoning VARCHAR(MAX) NOT NULL,
	job_skills_required VARCHAR(MAX) NOT NULL,
	job_posting_quality_score TINYINT NOT NULL,
	job_posting_quality_score_reasoning VARCHAR(MAX) NOT NULL,
	job_apply_link VARCHAR(255),
	job_rating_model_name VARCHAR(255) NOT NULL,
	resume_id INT NOT NULL
)